### ISSUE TITLE
Go Mod needs updating

### ISSUE THREAD

**Issue by Linesmerrill** [webgoprojects/go-mux-template#1]
The Go mod file needs to be updated. I can open a PR if you would like?

**Comment by webgoproject** [comment]
Thank you for your suggestion. Could you update the `go.mod` in a PR? I will review when I am able.

**Comment by Linesmerrill** [comment]
Yes sure thing! Thanks!

**Comment by Linesmerrill** [comment]
PR with that update is here: https://github.com/webgoprojects/go-mux-template/pull/2

**Comment by webgoproject** [comment]
Looking
